openapi: 3.0.0
info:
  title: Warehouse API
  description: >
    **Alpha Release**


    **This API and its documentation is not finalized yet and may change at

    any time without notice.**


    This is the documentation of the Zaikio Warehouse API Endpoints.

    ## Provided OAuth Scopes

    - `warehouse.finished_goods_call_offs.r`,
    `warehouse.finished_goods_call_offs.w`,
    `warehouse.finished_goods_call_offs.rw` [`Organization`]: Managing the
    finished goods call offs for the authorized customer

    - `warehouse.finished_goods_materials.r` [`Organization`]: Information about
    the available finished goods that are owned by the authorized customer
  version: 1.0.0
servers:
  - url: 'https://warehouse.zaikio.com/api/v1/'
    description: Production server (uses live data)
  - url: 'https://warehouse.sandbox.zaikio.com/api/v1/'
    description: Sandbox server (uses test data)
tags:
  - name: GoodsCallOffs
  - name: Materials
paths:
  /finished_goods/call_offs:
    post:
      summary: Create new goods call off
      tags:
        - GoodsCallOffs
      description: >
        Creates a  goods call off for the current organization.

        - needed bearer: `Organization`

        - needed scopes: `warehouse.finished_goods_call_offs.w` or
        `warehouse.finished_goods_call_offs.rw`
      security:
        - directoryAuth: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - goods_call_off
              properties:
                goods_call_off:
                  type: object
                  additionalProperties: false
                  required:
                    - delivery_date
                    - delivery_address_attributes
                    - line_items_attributes
                  properties:
                    delivery_date:
                      type: string
                      format: date-time
                      description: The desired delivery date
                      example: 2020-05-31T00:00:00.000Z
                    delivery_address_attributes:
                      type: object
                      additionalProperties: false
                      required:
                        - addressee
                        - text
                      properties:
                        addressee:
                          type: string
                          example: Crispy Mountain GmbH
                        text:
                          type: string
                          description: Address that will be parsed by Google
                          example: 'Emmerich-Josef-Straße 1A, 55116 Mainz'
                    line_items_attributes:
                      type: array
                      additionalProperties: false
                      items:
                        type: object
                        properties:
                          sku_id:
                            type: string
                            example: 81d724b5-4e2e-5615-819e-b20e0b23c4df
                          quantity:
                            type: integer
                            example: 5
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: &ref_2
                title: GoodsCallOff
                type: object
                additionalProperties: false
                required:
                  - id
                properties:
                  id: &ref_0
                    title: UUID
                    type: string
                    format: uuid
                    pattern: >-
                      [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
                  customer:
                    type: object
                    items: &ref_1
                      title: Organization
                      type: object
                      additionalProperties: false
                      required:
                        - id
                      properties:
                        id: *ref_0
                        name:
                          type: string
                          description: |
                            The name of the company
                        updated_at:
                          type: string
                          format: date-time
                        created_at:
                          type: string
                          format: date-time
                  operator:
                    type: object
                    items: *ref_1
                  state:
                    type: string
                    enum:
                      - draft
                      - confirmed
                      - packed
                      - delivered
                  order_number:
                    type: string
                    description: |
                      The order number
                  delivery_date:
                    type: string
                    format: date
                  updated_at:
                    type: string
                    format: date-time
                  created_at:
                    type: string
                    format: date-time
                  delivery_address:
                    type: object
                    items:
                      type: object
                      nullable: true
                      required:
                        - id
                        - addressee
                        - street
                        - number
                        - zip_code
                        - town
                        - country_code
                        - state
                        - addition
                        - location
                        - created_at
                        - updated_at
                      additionalProperties: false
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: 95fd969d-684f-49f6-b17d-5f4e786c11a9
                        addressee:
                          type: string
                          example: Zaikio GmbH
                        street:
                          type: string
                          example: Emmerich-Josef-Straße
                        number:
                          type: string
                          example: 1A
                          nullable: true
                        zip_code:
                          type: string
                          example: '551166'
                        town:
                          type: string
                          example: Mainz
                        country_code:
                          type: string
                          example: DE
                          nullable: true
                        state:
                          type: string
                          example: Rheinland-Pfalz
                        addition:
                          type: string
                          nullable: true
                        location:
                          type: array
                          minItems: 2
                          maxItems: 2
                          description: Latitude and Longitude
                          items:
                            type: number
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                  line_items:
                    type: array
                    items:
                      title: GoodsCallOffLineItem
                      type: object
                      additionalProperties: false
                      required:
                        - id
                      properties:
                        id: *ref_0
                        sku:
                          type: object
                          items: &ref_3
                            title: SKU
                            type: object
                            additionalProperties: false
                            required:
                              - id
                            properties:
                              id: *ref_0
                              identifier:
                                type: string
                              owner_id: *ref_0
                              amount_in_base_unit:
                                type: integer
                              unit:
                                type: string
                              order_number:
                                type: string
                              width:
                                type: string
                                nullable: true
                              length:
                                type: string
                                nullable: true
                              height:
                                type: string
                                nullable: true
                              weight:
                                type: string
                                nullable: true
                              dimensions_unit:
                                type: string
                              weight_unit:
                                type: string
                              packed:
                                type: boolean
                              updated_at:
                                type: string
                                format: date-time
                              created_at:
                                type: string
                                format: date-time
                        quantity:
                          example: 10
                          type: integer
                          minimum: 1
                        updated_at:
                          type: string
                          format: date-time
                        created_at:
                          type: string
                          format: date-time
              example:
                id: 2583dcd7-7fda-48b2-9492-8d82845161f5
                state: draft
                order_number: a3ac6a8be3b87ca12389d07bbf967fa2
                delivery_date: '2020-04-30'
                created_at: '2020-03-15T15:11:30.419Z'
                updated_at: '2020-03-15T15:11:30.419Z'
                delivery_address:
                  id: 1f6cc2fb-2fbe-4168-9a25-df6ce446d4ed
                  addressee: Crispy Mountain GmbH
                  street: Pasewalker Straße
                  addition: null
                  number: '25'
                  zip_code: '13127'
                  town: Berlin
                  state: Berlin
                  country_code: DE
                  location:
                    - 52.5882204
                    - 13.4294955
                customer:
                  id: 2b493a57-d8b1-548e-8240-475ff2494689
                  name: Pharma Group Inc.
                  created_at: '2020-03-10T15:11:28.000Z'
                  updated_at: '2020-03-10T15:11:28.000Z'
                line_items:
                  - id: 17e057fa-8fd8-47f2-bb2d-548199221644
                    quantity: 1
                    created_at: '2020-03-15T15:11:30.422Z'
                    updated_at: '2020-03-15T15:11:30.422Z'
                    sku:
                      id: 3a0c9dfd-bc2b-5495-97f2-57153cc0c0fb
                      identifier: 1x box a 850x Package Leaflet Vaccine CFX
                      owner_id: 2b493a57-d8b1-548e-8240-475ff2494689
                      amount_in_base_unit: 850
                      unit: box
                      order_number: CFX-1234-5594
                      width: '1.0'
                      length: '1.0'
                      height: '1.0'
                      weight: '1.0'
                      dimensions_unit: m
                      weight_unit: kg
                      packed: true
                      created_at: '2020-03-15T15:11:29.008Z'
                      updated_at: '2020-03-15T15:11:29.008Z'
        '422':
          description: Unprocessable Entity (Validation error during creation)
          content:
            application/json:
              schema:
                title: ValidationErrors
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: object
                    example:
                      name:
                        - can't be blank
                    additionalProperties:
                      type: array
                      items:
                        type: string
              example:
                errors:
                  operator:
                    - must exist
                  line_items:
                    - is too short (minimum is 1 character)
    get:
      summary: Read all GoodsCallOffs
      description: >
        Returns all GoodsCallOffs where the authorized organization is either
        customer or operator.

        - needed bearer: `Organization`

        - needed scopes: `warehouse.finished_goods_call_offs.r` or
        `warehouse.finished_goods_call_offs.rw`
      tags:
        - GoodsCallOffs
      parameters: []
      security:
        - directoryAuth: []
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: *ref_2
              example:
                - id: b406000e-b271-5abb-9cc3-9b7128746bdc
                  state: draft
                  order_number: 67a537277f6bc2f331da3601d070c0ab
                  delivery_date: '2020-03-25'
                  created_at: '2020-03-15T15:11:29.004Z'
                  updated_at: '2020-03-15T15:11:29.004Z'
                  delivery_address:
                    id: b14d7a13-1038-5295-a322-33d28beba5cc
                    addressee: Pharma Group Inc.
                    street: Gutenbergring
                    addition: null
                    number: '17'
                    zip_code: '69168'
                    town: Wiesloch
                    state: Baden-Württemberg
                    country_code: DE
                    location:
                      - 49.2900757
                      - 0
                  customer:
                    id: 2b493a57-d8b1-548e-8240-475ff2494689
                    name: Pharma Group Inc.
                    created_at: '2020-03-10T15:11:28.000Z'
                    updated_at: '2020-03-10T15:11:28.000Z'
                  line_items:
                    - id: c57cc9dc-7ff4-5757-9595-aa4451319d03
                      quantity: 5
                      created_at: '2020-03-15T15:11:29.032Z'
                      updated_at: '2020-03-15T15:11:29.032Z'
                      sku:
                        id: 3a0c9dfd-bc2b-5495-97f2-57153cc0c0fb
                        identifier: 1x box a 850x Package Leaflet Vaccine CFX
                        owner_id: 2b493a57-d8b1-548e-8240-475ff2494689
                        amount_in_base_unit: 850
                        unit: box
                        order_number: CFX-1234-5594
                        width: '1.0'
                        length: '1.0'
                        height: '1.0'
                        weight: '1.0'
                        dimensions_unit: m
                        weight_unit: kg
                        packed: true
                        created_at: '2020-03-15T15:11:29.008Z'
                        updated_at: '2020-03-15T15:11:29.008Z'
                    - id: 73919b26-7a51-59f4-984c-6557fc69f5c4
                      quantity: 10
                      created_at: '2020-03-15T15:11:29.032Z'
                      updated_at: '2020-03-15T15:11:29.032Z'
                      sku:
                        id: 2b7fc06a-748e-5c94-8864-706c8366aeea
                        identifier: 1x box a 1500x Package Leaflet Nasal Spray NOS
                        owner_id: 2b493a57-d8b1-548e-8240-475ff2494689
                        amount_in_base_unit: 1500
                        unit: box
                        order_number: NOS-1234-5594
                        width: '1.0'
                        length: '1.0'
                        height: '1.0'
                        weight: '1.0'
                        dimensions_unit: m
                        weight_unit: kg
                        packed: true
                        created_at: '2020-03-15T15:11:29.008Z'
                        updated_at: '2020-03-15T15:11:29.008Z'
        '404':
          description: Not Found
  '/finished_goods/call_offs/{goods_call_off_id}':
    get:
      summary: Read specific goods call off by ID
      tags:
        - GoodsCallOffs
      description: >
        Returns the specified goods call off if the current organization is
        either customer or operator.

        - needed bearer: `Organization`

        - needed scopes: `warehouse.finished_goods_call_offs.r` or
        `warehouse.finished_goods_call_offs.rw`
      security:
        - directoryAuth: []
        - bearerAuth: []
      parameters:
        - in: path
          name: goods_call_off_id
          required: true
          schema: *ref_0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema: *ref_2
              example:
                id: b406000e-b271-5abb-9cc3-9b7128746bdc
                state: draft
                order_number: 1a664d038e4c8cdd7e706532d6ea8cc2
                delivery_date: '2020-03-25'
                created_at: '2020-03-15T15:11:29.004Z'
                updated_at: '2020-03-15T15:11:29.004Z'
                delivery_address:
                  id: b14d7a13-1038-5295-a322-33d28beba5cc
                  addressee: Pharma Group Inc.
                  street: Gutenbergring
                  addition: null
                  number: '17'
                  zip_code: '69168'
                  town: Wiesloch
                  state: Baden-Württemberg
                  country_code: DE
                  location:
                    - 49.2900757
                    - 0
                customer:
                  id: 2b493a57-d8b1-548e-8240-475ff2494689
                  name: Pharma Group Inc.
                  created_at: '2020-03-10T15:11:28.000Z'
                  updated_at: '2020-03-10T15:11:28.000Z'
                line_items:
                  - id: c57cc9dc-7ff4-5757-9595-aa4451319d03
                    quantity: 5
                    created_at: '2020-03-15T15:11:29.032Z'
                    updated_at: '2020-03-15T15:11:29.032Z'
                    sku:
                      id: 3a0c9dfd-bc2b-5495-97f2-57153cc0c0fb
                      identifier: 1x box a 850x Package Leaflet Vaccine CFX
                      owner_id: 2b493a57-d8b1-548e-8240-475ff2494689
                      amount_in_base_unit: 850
                      unit: box
                      order_number: CFX-1234-5594
                      width: '1.0'
                      length: '1.0'
                      height: '1.0'
                      weight: '1.0'
                      dimensions_unit: m
                      weight_unit: kg
                      packed: true
                      created_at: '2020-03-15T15:11:29.008Z'
                      updated_at: '2020-03-15T15:11:29.008Z'
                  - id: 73919b26-7a51-59f4-984c-6557fc69f5c4
                    quantity: 10
                    created_at: '2020-03-15T15:11:29.032Z'
                    updated_at: '2020-03-15T15:11:29.032Z'
                    sku:
                      id: 2b7fc06a-748e-5c94-8864-706c8366aeea
                      identifier: 1x box a 1500x Package Leaflet Nasal Spray NOS
                      owner_id: 2b493a57-d8b1-548e-8240-475ff2494689
                      amount_in_base_unit: 1500
                      unit: box
                      order_number: NOS-1234-5594
                      width: '1.0'
                      length: '1.0'
                      height: '1.0'
                      weight: '1.0'
                      dimensions_unit: m
                      weight_unit: kg
                      packed: true
                      created_at: '2020-03-15T15:11:29.008Z'
                      updated_at: '2020-03-15T15:11:29.008Z'
        '404':
          description: Not Found
  /finished_goods/materials:
    get:
      summary: Read all materials owned by authorized organization
      tags:
        - Materials
      description: |
        Fetches all materials owned by the current organization.
        - needed bearer: `Organization`
        - needed scopes: `warehouse.finished_goods_materials.r`
      security:
        - directoryAuth: []
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Material
                  type: object
                  additionalProperties: false
                  required:
                    - id
                  properties:
                    id: *ref_0
                    operator_id: *ref_0
                    name:
                      type: string
                    kind:
                      type: string
                      enum:
                        - source_material
                        - semi_finished_good
                        - finished_good
                    category:
                      type: string
                    base_unit:
                      type: string
                    width:
                      type: string
                      nullable: true
                    length:
                      type: string
                      nullable: true
                    height:
                      type: string
                      nullable: true
                    weight:
                      type: string
                      nullable: true
                    dimensions_unit:
                      type: string
                    weight_unit:
                      type: string
                    updated_at:
                      type: string
                      format: date-time
                    created_at:
                      type: string
                      format: date-time
                    skus:
                      type: array
                      items: *ref_3
              example:
                - id: 96e0ad0d-bfe1-56f9-8d37-3a336611016b
                  operator_id: b1475f65-236c-58b8-96e1-e1778b43beb7
                  name: Package Leaflet Nasal Spray NOS
                  kind: finished_good
                  category: leaflet
                  base_unit: piece
                  width: null
                  length: null
                  height: null
                  weight: null
                  dimensions_unit: m
                  weight_unit: kg
                  created_at: '2020-03-15T15:11:28.996Z'
                  updated_at: '2020-03-15T15:11:28.996Z'
                  skus:
                    - id: 2b7fc06a-748e-5c94-8864-706c8366aeea
                      identifier: '1x box a 1500x Package Leaflet Nasal Spray NOS '
                      owner_id: 2b493a57-d8b1-548e-8240-475ff2494689
                      amount_in_base_unit: 1500
                      unit: box
                      order_number: NOS-1234-5594
                      width: '1.0'
                      length: '1.0'
                      height: '1.0'
                      weight: '1.0'
                      dimensions_unit: m
                      weight_unit: kg
                      packed: true
                      created_at: '2020-03-15T15:11:29.008Z'
                      updated_at: '2020-03-15T15:11:29.008Z'
                - id: 3dc4a496-7eac-5b05-99a4-bdcb01c1d0a2
                  operator_id: b1475f65-236c-58b8-96e1-e1778b43beb7
                  name: Package Leaflet Vaccine CFX
                  kind: finished_good
                  category: leaflet
                  base_unit: piece
                  width: null
                  length: null
                  height: null
                  weight: null
                  dimensions_unit: m
                  weight_unit: kg
                  created_at: '2020-03-15T15:11:28.996Z'
                  updated_at: '2020-03-15T15:11:28.996Z'
                  skus:
                    - id: 3a0c9dfd-bc2b-5495-97f2-57153cc0c0fb
                      identifier: '1x box a 850x Package Leaflet Vaccine CFX '
                      owner_id: 2b493a57-d8b1-548e-8240-475ff2494689
                      amount_in_base_unit: 850
                      unit: box
                      order_number: CFX-1234-5594
                      width: '1.0'
                      length: '1.0'
                      height: '1.0'
                      weight: '1.0'
                      dimensions_unit: m
                      weight_unit: kg
                      packed: true
                      created_at: '2020-03-15T15:11:29.008Z'
                      updated_at: '2020-03-15T15:11:29.008Z'
components:
  securitySchemes:
    directoryAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://directory.zaikio.com/oauth/authorize'
          tokenUrl: 'https://directory.zaikio.com/oauth/access_token.json'
          refreshUrl: 'https://directory.zaikio.com/oauth/access_token.json'
          scopes:
            warehouse.goods_call_off.rw: Manage goods call offs
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
